-- ================================================
-- INSERT ACTIVE SUPPLIERS
-- ================================================
-- This migration adds 5 active suppliers to the database
-- Generated on: 2025-11-11
-- ================================================

-- Insert Supplier 1: Lin (Lin Mobile) - China
INSERT INTO lats_suppliers (
    id,
    name,
    company_name,
    contact_person,
    email,
    phone,
    whatsapp,
    wechat,
    address,
    city,
    country,
    is_active,
    notes,
    preferred_currency,
    payment_days,
    priority_level,
    credit_limit,
    current_balance,
    discount_percentage,
    total_orders,
    total_order_value,
    average_rating,
    on_time_delivery_rate,
    quality_score,
    is_trade_in_customer,
    is_shared,
    branch_id,
    created_at,
    updated_at
) VALUES (
    'd2e1564d-3de9-4385-b4e2-539973d698bb',
    'Lin',
    'Lin Mobile',
    NULL,
    NULL,
    '+86 135 3893 8890',
    '+86 135 3893 8890',
    'lin008',
    'Doshatou',
    'Guangzhou',
    'China',
    true,
    'Product Categories: iPhones',
    'CNY',
    30,
    'standard',
    0.00,
    0.00,
    0.00,
    0,
    0.00,
    0.00,
    0.00,
    0.00,
    false,
    true,
    NULL,
    '2025-11-11 02:25:48.844+00',
    '2025-11-11 02:25:48.844+00'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    company_name = EXCLUDED.company_name,
    phone = EXCLUDED.phone,
    whatsapp = EXCLUDED.whatsapp,
    wechat = EXCLUDED.wechat,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    country = EXCLUDED.country,
    is_active = EXCLUDED.is_active,
    notes = EXCLUDED.notes,
    preferred_currency = EXCLUDED.preferred_currency,
    updated_at = now();

-- Insert Supplier 2: Rabnawaz (Sahel Al Khor) - UAE
INSERT INTO lats_suppliers (
    id,
    name,
    company_name,
    contact_person,
    email,
    phone,
    whatsapp,
    address,
    city,
    country,
    is_active,
    notes,
    preferred_currency,
    payment_days,
    priority_level,
    credit_limit,
    current_balance,
    discount_percentage,
    total_orders,
    total_order_value,
    average_rating,
    on_time_delivery_rate,
    quality_score,
    is_trade_in_customer,
    is_shared,
    branch_id,
    created_at,
    updated_at
) VALUES (
    '85072217-3807-409a-92e0-80b5b4914ad4',
    'Rabnawaz',
    'Sahel Al Khor',
    NULL,
    NULL,
    '+971 50 928 0578',
    '+971 50 928 0578',
    'Sharjah Industrial Area, Industrial Area, Sharjah, Sharjah Emirate, United Arab Emirates',
    'Sharjah',
    'UAE',
    true,
    'Product Categories: Soundbar, Laptops & Computers',
    'AED',
    30,
    'standard',
    0.00,
    0.00,
    0.00,
    0,
    0.00,
    0.00,
    0.00,
    0.00,
    false,
    true,
    NULL,
    '2025-11-11 02:31:23.349+00',
    '2025-11-11 02:31:23.349+00'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    company_name = EXCLUDED.company_name,
    phone = EXCLUDED.phone,
    whatsapp = EXCLUDED.whatsapp,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    country = EXCLUDED.country,
    is_active = EXCLUDED.is_active,
    notes = EXCLUDED.notes,
    preferred_currency = EXCLUDED.preferred_currency,
    updated_at = now();

-- Insert Supplier 3: Eddy Speaker - China
INSERT INTO lats_suppliers (
    id,
    name,
    company_name,
    contact_person,
    email,
    phone,
    whatsapp,
    wechat,
    address,
    city,
    country,
    is_active,
    notes,
    preferred_currency,
    payment_days,
    priority_level,
    credit_limit,
    current_balance,
    discount_percentage,
    total_orders,
    total_order_value,
    average_rating,
    on_time_delivery_rate,
    quality_score,
    is_trade_in_customer,
    is_shared,
    branch_id,
    created_at,
    updated_at
) VALUES (
    '6479c82a-34a8-4b0f-b1b0-aeab2bc2ba9a',
    'Eddy Speaker',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'EDDYSpeaker',
    'Caltual Park',
    'Guangzhou',
    'China',
    true,
    'Product Categories: Bluetooth Sperkers',
    'CNY',
    30,
    'standard',
    0.00,
    0.00,
    0.00,
    1,
    0.00,
    0.00,
    0.00,
    0.00,
    false,
    true,
    NULL,
    '2025-11-11 02:28:36.017+00',
    '2025-11-11 03:36:44.535+00'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    wechat = EXCLUDED.wechat,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    country = EXCLUDED.country,
    is_active = EXCLUDED.is_active,
    notes = EXCLUDED.notes,
    preferred_currency = EXCLUDED.preferred_currency,
    total_orders = EXCLUDED.total_orders,
    updated_at = now();

-- Insert Supplier 4: DUBAI - UAE
INSERT INTO lats_suppliers (
    id,
    name,
    company_name,
    contact_person,
    email,
    phone,
    whatsapp,
    address,
    city,
    country,
    is_active,
    notes,
    preferred_currency,
    payment_days,
    priority_level,
    credit_limit,
    current_balance,
    discount_percentage,
    total_orders,
    total_order_value,
    average_rating,
    on_time_delivery_rate,
    quality_score,
    is_trade_in_customer,
    is_shared,
    branch_id,
    created_at,
    updated_at
) VALUES (
    '3aeeda7f-a6a0-4ac6-9123-a8e53ca44b14',
    'DUBAI',
    'Non',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Deira',
    'UAE',
    true,
    'Product Categories: Laptops & Computers, Audio & Headphones, Smartphones & Tablets',
    'AED',
    30,
    'standard',
    0.00,
    0.00,
    0.00,
    0,
    0.00,
    0.00,
    0.00,
    0.00,
    false,
    true,
    NULL,
    '2025-11-11 03:07:53.192+00',
    '2025-11-11 03:07:53.192+00'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    company_name = EXCLUDED.company_name,
    city = EXCLUDED.city,
    country = EXCLUDED.country,
    is_active = EXCLUDED.is_active,
    notes = EXCLUDED.notes,
    preferred_currency = EXCLUDED.preferred_currency,
    updated_at = now();

-- Insert Supplier 5: CHINA - China
INSERT INTO lats_suppliers (
    id,
    name,
    company_name,
    contact_person,
    email,
    phone,
    whatsapp,
    address,
    city,
    country,
    is_active,
    notes,
    preferred_currency,
    payment_days,
    priority_level,
    credit_limit,
    current_balance,
    discount_percentage,
    total_orders,
    total_order_value,
    average_rating,
    on_time_delivery_rate,
    quality_score,
    is_trade_in_customer,
    is_shared,
    branch_id,
    created_at,
    updated_at
) VALUES (
    'aa9168d0-fa8b-484a-a44c-771fbc5c240f',
    'CHINA',
    'Non',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Guangzhou',
    'China',
    true,
    'Product Categories: iPhones, Smartphones & Tablets, Bluetooth Sperkers, Accessories & Cables',
    'CNY',
    30,
    'standard',
    0.00,
    0.00,
    0.00,
    0,
    0.00,
    0.00,
    0.00,
    0.00,
    false,
    true,
    NULL,
    '2025-11-11 03:08:58.640+00',
    '2025-11-11 03:08:58.640+00'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    company_name = EXCLUDED.company_name,
    city = EXCLUDED.city,
    country = EXCLUDED.country,
    is_active = EXCLUDED.is_active,
    notes = EXCLUDED.notes,
    preferred_currency = EXCLUDED.preferred_currency,
    updated_at = now();

-- ================================================
-- MIGRATION COMPLETE ✅
-- ================================================
-- Successfully inserted 5 active suppliers:
-- 1. Lin (Lin Mobile) - China, Guangzhou
-- 2. Rabnawaz (Sahel Al Khor) - UAE, Sharjah
-- 3. Eddy Speaker - China, Guangzhou
-- 4. DUBAI - UAE, Deira
-- 5. CHINA - China, Guangzhou
-- ================================================

